# Generated by Django 3.0 on 2025-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compensacaoprevidenciaria',
            name='pk_CompensacaoPrevidenciaria',
        ),
        migrations.RenameField(
            model_name='compensacaoprevidenciaria',
            old_name='Tipofundo',
            new_name='TipoFundo',
        ),
        migrations.AlterField(
            model_name='carteirainvestimento',
            name='PatrimonioLiquidoAtivo',
            field=models.DecimalField(decimal_places=8, max_digits=28),
        ),
        migrations.AlterField(
            model_name='carteirainvestimento',
            name='QuantidadeCotas',
            field=models.DecimalField(decimal_places=8, max_digits=28),
        ),
        migrations.AlterField(
            model_name='carteirainvestimento',
            name='ValorCota',
            field=models.DecimalField(decimal_places=8, max_digits=28),
        ),
        migrations.AlterUniqueTogether(
            name='carteirainvestimento',
            unique_together={('TipoFundo', 'Ano', 'Mes', 'CNPJAtivo', 'Seguimento', 'Enquadramento')},
        ),
        migrations.AddConstraint(
            model_name='compensacaoprevidenciaria',
            constraint=models.UniqueConstraint(fields=('ano_ref', 'mes_ref', 'TipoFundo', 'CNPJPagador'), name='pk_CompensacaoPrevidenciaria'),
        ),
    ]
