# Generated by Django 3.0 on 2025-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0002_auto_20250528_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rppsestrutura',
            name='entrada_espec',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Opções para Select'),
        ),
    ]
