# Generated by Django 5.2.7 on 2025-10-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0003_auto_20250717_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='rppsestrutura',
            name='campo_display_referencia',
            field=models.TextField(blank=True, help_text="Mapeamento entre campos locais e campos da tabela de referência (ex: 'a=CPF,b=endereco,c=nome')", null=True, verbose_name='Mapeamento de Campos de Retorno'),
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('CpfCnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'db_table': 'Cadastro',
                'unique_together': {('CpfCnpj',)},
            },
        ),
    ]
