# Generated by Django 5.2.7 on 2025-10-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0004_rppsestrutura_campo_display_referencia_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteirainvestimento',
            name='CNPJAtivo',
            field=models.ForeignKey(blank=True, db_column='CNPJAtivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carteira_ativo', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='certificacaorpps',
            name='CNPJCertificadora',
            field=models.ForeignKey(blank=True, db_column='CNPJCertificadora', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificadora', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='certificacaorpps',
            name='CNPJEnteFederativo',
            field=models.ForeignKey(blank=True, db_column='CNPJEnteFederativo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificacao_ente', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='certificadoregularidadeprevidenciaria',
            name='CNPJEnte',
            field=models.ForeignKey(blank=True, db_column='CNPJEnte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificado_ente', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='compensacaoprevidenciaria',
            name='CNPJPagador',
            field=models.ForeignKey(blank=True, db_column='CNPJPagador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensacao_pagador', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='gestorfinanceiro',
            name='CPF',
            field=models.ForeignKey(blank=True, db_column='CPF', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestor_financeiro', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='membrocolegio',
            name='CPF',
            field=models.ForeignKey(blank=True, db_column='CPF', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membro_colegio', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='parcelamento',
            name='CNPJOrgaoParcelamento',
            field=models.ForeignKey(blank=True, db_column='CNPJOrgaoParcelamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelamento_orgao', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='parcelasparcelamento',
            name='CNPJOrgaoParcelamento',
            field=models.ForeignKey(blank=True, db_column='CNPJOrgaoParcelamento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_orgao', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='resultadoatuarial',
            name='CPFAtuario',
            field=models.ForeignKey(blank=True, db_column='CPFAtuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atuario', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='rpps',
            name='CNPJEnteFederativo',
            field=models.ForeignKey(blank=True, db_column='CNPJEnteFederativo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpps_ente', to='app_rpps.cadastro'),
        ),
        migrations.AlterField(
            model_name='rpps',
            name='CNPJRPPS',
            field=models.ForeignKey(blank=True, db_column='CNPJRPPS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rpps_rpps', to='app_rpps.cadastro'),
        ),
    ]
