# Generated by Django 5.2.5 on 2026-01-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0005_convert_cpf_cnpj_to_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoatuarial',
            old_name='DeficitAtuarial',
            new_name='ResultadoAtuarial',
        ),
    ]
