# Generated by Django 5.2.7 on 2026-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0006_rename_deficit_to_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rppsestrutura',
            name='referencia_config',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Estrutura formal para tabela, campo de referência, filtros e dependências',
                null=True,
                verbose_name='Configuração estruturada de referência',
            ),
        ),
    ]
