# Generated by Django 5.2.17 on 2026-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rpps', '0007_rppsestrutura_referencia_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhamentometaatuarial',
            options={'managed': False, 'verbose_name': 'Acompanhamento Meta Atuarial', 'verbose_name_plural': 'Acompanhamento Metas Atuariais'},
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'managed': False, 'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
        migrations.AlterModelOptions(
            name='carteirainvestimento',
            options={'managed': False, 'verbose_name': 'Carteira Investimento', 'verbose_name_plural': 'Carteiras Investimento'},
        ),
        migrations.AlterModelOptions(
            name='certificacaorpps',
            options={'managed': False, 'verbose_name': 'CertificacaoRPPS', 'verbose_name_plural': 'Membro Colegio'},
        ),
        migrations.AlterModelOptions(
            name='certificadoregularidadeprevidenciaria',
            options={'managed': False, 'verbose_name': 'Certificado Regularidade Previdenciaria', 'verbose_name_plural': 'Certificados Regularidades Previdenciaria'},
        ),
        migrations.AlterModelOptions(
            name='compensacaoprevidenciaria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estruturamenu',
            options={'managed': False, 'ordering': ['ordem_menu', 'label'], 'verbose_name': 'Item de Menu', 'verbose_name_plural': 'Itens de Menu'},
        ),
        migrations.AlterModelOptions(
            name='fundo',
            options={'managed': False, 'verbose_name': 'Fundo', 'verbose_name_plural': 'Fundos'},
        ),
        migrations.AlterModelOptions(
            name='gerxml',
            options={'managed': False, 'verbose_name': 'Gerxml', 'verbose_name_plural': 'Gerxml'},
        ),
        migrations.AlterModelOptions(
            name='gestorfinanceiro',
            options={'managed': False, 'verbose_name': 'Gestor Financeiro', 'verbose_name_plural': 'Gestores Financeiro'},
        ),
        migrations.AlterModelOptions(
            name='gruposcolegiados',
            options={'managed': False, 'verbose_name': 'Grupos Colegiados', 'verbose_name_plural': 'Grupos Colegiados'},
        ),
        migrations.AlterModelOptions(
            name='membrocolegio',
            options={'managed': False, 'verbose_name': 'MembroColegio', 'verbose_name_plural': 'Membro Colegio'},
        ),
        migrations.AlterModelOptions(
            name='parcelamento',
            options={'managed': False, 'verbose_name': 'Parcelamento', 'verbose_name_plural': 'Parcelamentos'},
        ),
        migrations.AlterModelOptions(
            name='parcelasparcelamento',
            options={'managed': False, 'verbose_name': 'Parcelamento', 'verbose_name_plural': 'PoPArcelamentos'},
        ),
        migrations.AlterModelOptions(
            name='planocusteio',
            options={'managed': False, 'verbose_name': 'Plano Custeio', 'verbose_name_plural': 'Planos Custeio'},
        ),
        migrations.AlterModelOptions(
            name='politicainvestimento',
            options={'managed': False, 'verbose_name': 'Politica Investimento', 'verbose_name_plural': 'Politica Investimentos'},
        ),
        migrations.AlterModelOptions(
            name='resultadoatuarial',
            options={'managed': False, 'verbose_name': 'Resultado Atuarial', 'verbose_name_plural': 'Resultado Atuarial'},
        ),
        migrations.AlterModelOptions(
            name='rpps',
            options={'managed': False, 'verbose_name': 'RPPS', 'verbose_name_plural': 'RPPS'},
        ),
        migrations.AlterModelOptions(
            name='rppsestrutura',
            options={'managed': True, 'ordering': ['nome_tabela', 'ordem_campo'], 'verbose_name': 'Estrutura RPPS', 'verbose_name_plural': 'Estruturas RPPS'},
        ),
        migrations.AlterModelOptions(
            name='tbveipub',
            options={'managed': False, 'verbose_name': 'Veiculo Publico', 'verbose_name_plural': 'Veiculos Publico'},
        ),
        migrations.AlterModelOptions(
            name='tipoxml',
            options={'managed': False, 'verbose_name': 'Tipo do movimento para o Xml', 'verbose_name_plural': 'Tipos do movimentos para o Xml'},
        ),
        migrations.AlterField(
            model_name='rppsestrutura',
            name='referencia_config',
            field=models.TextField(blank=True, help_text='Estrutura formal para tabela, campo de referência, filtros e dependências (armazenado como JSON)', null=True, verbose_name='Configuração estruturada de referência'),
        ),
    ]
